# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#papers
    weight: 11
  - name: Talks
    url: /#talks
    weight: 12
  - name: Current Research
    url: projects/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
  - name: Professional Experience
    url: '#experience'
    weight: 20
  - name: Contact
    url: '#contact'
    weight: 60
  - name: CV
    url: uploads/resume.pdf
    weight: 70
  
